import { Power, Rank } from "../types";

export const powers: Power[] = [
  {
    id: "1",
    name: "Arcane Protection",
    alternateName: null,
    relatedPowers: [],
    rank: Rank.Novice,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary:
      "Enemy casters subtract 2 (4 with a raise) when targeting this character; reduces damage a like amount.",
    trappings: [
      "Concentration",
      "a dull glow around the protected character",
      "a fetish.",
    ],
    fullDescription:
      "Success with arcane protection means hostile powers suffer a -2 penalty (-4 with a raise) to affect this character. If the power causes harm, damage is also reduced a like amount. Arcane protection stacks with Arcane Resistance should the recipient have both!",
    pageNum: 154,
    powerModifiers: ["2"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Opposed roll vs Spirit to <i>banish </i>entities.",
    trappings: ["Holy items", " arcane symbols", " handful of salt."],
    fullDescription:
      "<i>Banish</i> sends entities from immaterial planes back to their native dimensions. This includes ghosts, demons, elementals, and similar beings (at the GM's discretion).<br>\n" +
      "<i>Banishing</i> a being is an opposed roll of the caster's arcane skill versus the target's Spirit. Success means the target is Shaken, and each raise causes a Wound.<br>\n" +
      "If this Incapacitates the target, it returns to its native plane of existence. <i>Banished</i> entities may return when the Game Master feels it's appropriate, such as the next full moon, when summoned again, or even a few rounds later if it's a particularly powerful creature under the right conditions or in a location of power.",
    pageNum: 154,
    powerModifiers: [],
    id: "2",
    name: "Banish",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary:
      "Creates 5&quot; (10 yards) long, 1&quot; (2 yards) tall, Hardness 10 barrier.",
    trappings: ["Fire", " ice", " thorns", " force", " bones", " energy."],
    fullDescription:
      "<i>Barrier</i> creates a straight wall 5&quot; (10 yards) long and 1&quot; (two yards) tall, of immobile material that conforms to the surface it's cast upon. Thickness varies depending on what the wall is made of, but is usually a few inches.<br>The wall has a Hardness of 10, and may be destroyed as any other object (see <strong>Breaking Things </strong>on page 98).<br>When the spell expires or the wall is broken it crumbles to dust or dissipates. Trappings are never left behind.",
    pageNum: 155,
    powerModifiers: ["53", "52", "34", "24"],
    id: "3",
    name: "Barrier",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "Special",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 10,
    summary: "Controls animals.",
    trappings: ["The caster concentrates and gestures with his hands."],
    fullDescription:
      "<i>Beast Friend</i> allows an individual to speak with and guide the actions of nature's beasts. The cost to cast is equal to the sum of their Size (minimum 1 per creature; see the creatures in Chapter Six for examples). Controlling five wolves (Size -1) costs 5 points (remember the minimum cost of 1), for example. Controlling a single rhino (Size 5) costs 5 points.<br>Success means the creatures obey simple commands, like a well-trained dog. They attack foes and endanger their lives for their master. A raise on the arcane skill roll means the beasts are more obedient. They won't kill themselves but overcome their natural fears to follow their orders.<br>Swarms can also be controlled. Small Swarms cost 1 point, Medium Swarms cost 2, and Large Swarms cost 3.<br><i>Beast friend</i> works only on natural creatures with animal intelligence, not humanoids, and has no effect on conjured, magical, or otherwise &quot;unnatural&quot; animals.",
    pageNum: 155,
    powerModifiers: ["21", "20", "19", "18", "17", "35"],
    id: "4",
    name: "Beast Friend",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: 2,
    duration: "Instant",
    durationMultiplier: null,
    summary: "2d6 damage in Medium Blast Template.",
    trappings: [
      "Balls of fire",
      " ice",
      " light",
      " darkness",
      " colored bolts",
      " swarm of insects.",
    ],
    fullDescription:
      "<i>Blast</i> launches a ball of explosive energy or matter. The area of effect is a Medium Blast Template. Every target within suffers 2d6 damage, or 3d6 with a raise (see <strong>Area Effect Attacks</strong>, page 97).",
    pageNum: 156,
    powerModifiers: ["25", "9", "7"],
    id: "5",
    name: "Blast",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Inflicts -2/-4 penalty to victims.",
    trappings: ["Bright flash of light", " sand in eyes", " confusion."],
    fullDescription:
      "Those affected by this malicious power suffer blurred vision or near-complete <i>blindness</i> with a raise.<br>Success means the victim suffers a -2 penalty to all actions requiring sight, or -4 with a raise.<br>The victim automatically tries to shake off the effect with a Vigor roll as a free action at the end of his following turns. Success removes 2 points of penalties, and a raise removes the effect entirely.",
    pageNum: 156,
    powerModifiers: ["60", "13", "11"],
    id: "6",
    name: "Blind",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: 2,
    duration: "Instant",
    durationMultiplier: null,
    summary: "2d6 ranged attack.",
    trappings: [
      "Fire",
      " ice",
      " light",
      " darkness",
      " colored bolts",
      " a stream of insects.",
    ],
    fullDescription:
      "<i>Bolt</i> sends damaging bursts of energy, streaks of holy light, or shards of matter toward one's foes.<br>There are no Range penalties, but the arcane skill roll is affected by Cover, Illumination, and all other usual penalties.<br>The damage of the bolt is 2d6, or 3d6 with a raise.",
    pageNum: 156,
    powerModifiers: ["26"],
    id: "7",
    name: "Bolt",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Increases or decreases a skill or attribute.",
    trappings: ["Physical change", " glowing aura", " potions."],
    fullDescription:
      "This power allows a character to increase or decrease a target's Trait (attribute or skill).<br><i>Boosting</i> an ally's Trait increases the selected Trait one die type, or two with a raise, for five rounds.<br>Additional castings don't stack on a single Trait (take the highest), but may affect different Traits.",
    pageNum: 156,
    powerModifiers: ["2"],
    id: "8",
    name: "Boost Trait",
    relatedPowers: ["36"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Target tunnels through the earth.",
    trappings: ["Dissolving into the earth and appearing elsewhere."],
    fullDescription:
      "<i>Burrow</i> allows the recipient to meld into raw earth. He can remain underground if he wants in a sort of &quot;limbo&quot; or <i>burrow</i> through the ground at half his normal Pace (or full Pace with a raise). He may not run.<br>A burrowing character may attempt to surprise a foe by making an opposed Stealth versus Notice roll. If the burrower wins, the target is Vulnerable to him only. With a raise, the burrower gets the Drop. Targets on Hold may attempt to interrupt the attack before it occurs.<br>Burrowers can't usually surprise a foe once their presence is known, but can still burrow for protection and mobility.",
    pageNum: 157,
    powerModifiers: ["44", "2"],
    id: "9",
    name: "Burrow",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Cone",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Cone-shaped attack for 2d6 damage.",
    trappings: ["A shower of flames", " light", " or other matter or energy."],
    fullDescription:
      "<i>Burst</i> produces a large fan of energy that bathes its targets in red-hot fire, a cone of cold, or other damaging matter or energy.<br>Success creates a Cone Template starting at the caster and extending outward (see <strong>Area Effect Attacks</strong>, page 97). Everything within suffers 2d6 damage (or 3d6 with a raise).",
    pageNum: 157,
    powerModifiers: ["27"],
    id: "10",
    name: "Burst",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Hour",
    durationMultiplier: 1,
    summary: "Detects magic for Duration 5 or conceals it for one hour.",
    trappings: ["Waving hands", " whispered words."],
    fullDescription:
      "<i>Conceal arcana</i> prevents detection of arcane energies on one being or item of Normal Scale for one hour (see the Size Table page 179).<br><strong>Detect vs. Conceal:</strong> Detecting arcana against someone or something that's been concealed is an opposed roll of arcane skills (roll each time it's attempted, but no more than once per turn). If the concealment wins, the character cannot see through the ruse with this casting, but may terminate this instance and try again.",
    pageNum: 158,
    powerModifiers: ["57", "12", "10", "1"],
    id: "11",
    name: "Conceal Arcana",
    relatedPowers: ["17"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Until the end of the victim's next turn",
    durationMultiplier: null,
    summary: "Makes target Distracted and Vulnerable.",
    trappings: ["Hypnotic lights", " brief illusions", " loud noises."],
    fullDescription:
      "<i>Confusion</i> confounds a target, making him both Distracted and Vulnerable if he fails a Smarts roll (at -2 with a raise on the arcane skill roll). Both states are removed at the end of the victim's next turn.",
    pageNum: 157,
    powerModifiers: ["13", "11"],
    id: "12",
    name: "Confusion",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "4",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Creates aura that causes 2d4 damage.",
    trappings: ["Fiery aura", " spikes", " electrical field."],
    fullDescription:
      "<i>Damage field</i> creates a dangerous aura around the recipient that harms foes foolish enough to get too close.<br>At the end of the affected character's turn, all adjacent beings (including allies!) automatically take 2d4 damage.",
    pageNum: 157,
    powerModifiers: ["28"],
    id: "13",
    name: "Damage Field",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 10,
    summary: "Dispels illumination.",
    trappings: ["Darkness", " thick fogs."],
    fullDescription:
      "<i>Darkness</i> blocks illumination in an area the size of a Large Blast Template, making the area Dark, or Pitch Darkness with a raise (see Illumination on page 102).<br>If <i>light</i> and <i>darkness</i> overlap, they create a patch of Dim light (-2).",
    pageNum: 164,
    powerModifiers: ["38"],
    id: "14",
    name: "Darkness",
    relatedPowers: ["35"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Hour",
    durationMultiplier: 1,
    summary:
      "Ignore up to 4 points of illumination penalties, or 6 with a raise.",
    trappings: ["Glowing eyes", " dilated pupils", " sonic sight."],
    fullDescription:
      "<i>Darksight</i> allows a hero to see in the dark. With success, he ignores up to 4 points of illumination penalties. With a raise, he ignores up to six points and can see in pitch darkness.",
    pageNum: 157,
    powerModifiers: ["2"],
    id: "15",
    name: "Darksight",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "-2/-4 to attack recipient.",
    trappings: [
      "Mystical shield",
      " gust of wind",
      " phantom servant that intercepts missiles.",
    ],
    fullDescription:
      "<i>Deflection</i> powers work in a variety of ways. Some manifestations actually deflect incoming attacks, others blur the target's form or produce illusionary effects. The end result is always the same, however&#8212;to misdirect incoming melee and missile attacks from the recipient of the power.<br>Once cast, foes must subtract 2 from attack rolls directed at the user (or 4 with a raise).",
    pageNum: 158,
    powerModifiers: ["2"],
    id: "16",
    name: "Deflection",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Detects magic for Duration 5 or conceals it for one hour.",
    trappings: ["Waving hands", " whispered words."],
    fullDescription:
      "<i>Detect arcana</i> allows the recipient of the power to see and detect all supernatural persons, objects, or effects in sight for five rounds. This includes invisible foes, enchantments on people or items, weird science devices, and so on. With a raise, the caster knows the general type of enchantment as well&#8212;harmful, obscurement, magic, miracles, etc.<br><i>Detect arcana</i> also allows a character to ignore up to 4 points of penalties when attacking foes hidden by magical darkness, invisibility, or similar abilities (or all penalties with a raise).<br><strong>Detect vs. Conceal:</strong> Detecting arcana against someone or something that's been concealed is an opposed roll of arcane skills (roll each time it's attempted, but no more than once per turn). If the concealment wins, the character cannot see through the ruse with this casting, but may terminate this instance and try again.",
    pageNum: 158,
    powerModifiers: ["3"],
    id: "17",
    name: "Detect Arcana",
    relatedPowers: ["11"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 10,
    summary: "Target looks like someone else.",
    trappings: [
      "Malleable features",
      " illusionary appearance",
      " hair of new form.",
    ],
    fullDescription:
      "<i>Disguise</i> allows the target to assume the appearance of another person of the same Size and shape, including clothing. It does not confer any abilities, however.<br>Those who have reason to question the imposter's identity make a Notice roll at -2 to see through the disguise (-4 with a raise on the casting roll). This is a free action.",
    pageNum: 158,
    powerModifiers: ["54", "2"],
    id: "18",
    name: "Disguise",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Negates magical effects.",
    trappings: ["Waving hands", " whispered words."],
    fullDescription:
      "<i>Dispel</i> allows a hero to negate enemy powers. It has no effect on permanent enchantments or innate abilities such as a dragon's breath or a banshee's scream. <i>Dispel</i> affects arcane devices normally (see <strong>Arcane Devices</strong>, page 153).<br><i>Dispel</i> can be used on a power already in effect or to counter an enemy power as it's being used. The latter requires the countering mage to be on Hold and interrupt his foe's action.<br>In either case, <i>dispelling</i> an opponent's power is an opposed roll of arcane skills (with a -2 modifier if the rival's power is of another type such as magic vs. miracles, psionics vs. weird science, etc.).<br>If the <i>dispelling</i> character wins, the targeted power ends immediately (or fails if it was countered with the usual results of failure). With a raise, the recipient of the dispelled power is also Distracted.",
    pageNum: 158,
    powerModifiers: ["43"],
    id: "19",
    name: "Dispel",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "5",
    range: "Self",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 5,
    summary: "Caster asks questions of entities.",
    trappings: ["Seances", " prayers", " demonic interrogation."],
    fullDescription:
      "<i>Divination</i> allows the caster to contact otherworldly beings or forces to gain information.<br>Preparing the spell takes one uninterrupted minute, and must be done at a site relevant to the spirit being contacted. If speaking with a ghost, for example, the conversation should occur at its grave, where it was killed, or with a personal object in hand. Oracles may only be engaged at temples, fire spirits near open flames, and so on.<br>After the preparation time is complete, the caster makes her arcane skill roll. Success allows her to engage with the spirit and ask it any questions she might have. The entity must answer to the best of its ability, as directly or ambiguously as the Game Master feels fits the spirit's personality and the feel of her campaign. A raise means the spirit is more helpful, knowledgeable, or direct than usual (whether it wants to be or not).<br>The type of entity contacted determines how it communicates. Spirits in the netherworld tend to know only those things pertinent to their life and death&#8212;and they may not even know the identity of their killer if the person was masked or unseen.<br>Likewise, nature spirits know only about their local environs, demons know only about the affairs they're directly involved in, and so on. The Game Master must decide what the entity knows based on its background, origin, and personality.<br>Once a spirit has been conversed with it may not be contacted again for 24 hours. The Game Master may extend this to a community of spirits in a single place, such as water spirits in a babbling brook or nameless spirits in a mass grave.",
    pageNum: 159,
    powerModifiers: [],
    id: "20",
    name: "Divination",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary:
      "Drains d6 Power Points from enemy with successful opposed roll of arcane skills.",
    trappings: ["Prayer", " whispered words", " gestures."],
    fullDescription:
      "Powerful mages, priests, psykers, and the like can use this ability to drain arcane energy from their foes. They can sometimes even leech the stolen energy for themselves.<br>The power is opposed by the target's Spirit, and the caster suffers a -2 penalty to their roll if the target has a different Arcane Background than their own.<br>Success drains 1d6 of the rival's Power Points (if any, and the die doesn't Ace). With a raise, the caster adds the points to her own. This <i>may</i> take above the caster's usual maximum! They last until used, and must be the first spent when casting.<br><i>Drain Power Points</i> can also be used on an arcane device (the creator still resists with her arcane skill whether the creator wields it or not). The device can't lose more Power Points than it has.",
    pageNum: 160,
    powerModifiers: [],
    id: "21",
    name: "Drain Power Points",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Allows minor manipulation of basic elements.",
    trappings: ["A few simple gestures."],
    fullDescription:
      "<i>Elemental manipulation</i> grants basic control over the four traditional elements: air, earth, fire, and water (the elements may vary depending on the setting). The power acts as if it has a d6 Strength, or d8 with a raise.<br>Here are some ideas for what each element can do. Each is an action.<br><ul><li><strong>AIR:</strong> Push someone, blow out a torch, fan a flame, cool someone down (+2 to Fatigue rolls in oppressive heat). </li><li><strong>EARTH: </strong>Move a square foot of earth (half that in stone) each round, cover tracks. </li><li><strong>FIRE: </strong>Conjure flame about the size of a torch, hurl a small blast of fire at someone (Str damage), spread existing flame (see Fire on page 127). </li><li><strong>WATER: </strong>Conjure a quart of water (not &quot;inside&quot; objects or people), purify a gallon of water per casting.</li></ul>",
    pageNum: 160,
    powerModifiers: [],
    id: "22",
    name: "Elemental Manipulation",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary:
      "Opposed roll vs Spirit to add +2 to social attacks for the Duration of the power.",
    trappings: [
      "Concentration",
      " a warm or sympathetic smile",
      " exchanging a pleasantry.",
    ],
    fullDescription:
      "The caster forms an emotional bond between himself and the target with a successful arcane skill vs Spirit roll. The caster knows the target's emotional state and most basic surface thoughts, and gains +1 (+2 with a raise) to Intimidation, Persuasion, Performance, or Taunt rolls against the target.<br><i>Empathy</i> also works on animals, adding +2 to Riding or other rolls used to interact with the creature.",
    pageNum: 160,
    powerModifiers: [],
    id: "23",
    name: "Empathy",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Bind or Entangle foes.",
    trappings: ["Glue bomb", " vines", " handcuffs", " webs."],
    fullDescription:
      "<i>Entangle</i> allows the caster to restrain a target with ice, bands of energy, or other vine-like Trappings (Hardness 5). If successful, the target is Entangled. With a raise, he's Bound.<br>Victims may break free on their turn as detailed under Bound & Entangled on page 98.",
    pageNum: 161,
    powerModifiers: ["62", "13", "11"],
    id: "24",
    name: "Entangle",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Hour",
    durationMultiplier: 1,
    summary: "Protect target from hazardous environments.",
    trappings: ["A mark on the forehead", " potions", " gills."],
    fullDescription:
      "Adventurers sometimes travel beneath the waves, in space, or other hazardous environments. This power protects them from crushing depths, scathing heat, intense cold, and even radiation.<br>Environmental protection allows the target to breathe, speak, and move at his normal Pace in an otherwise fatal environment. It protects him against intense heat, cold, radiation, atmospheric or fluid pressure, and lack of oxygen. Generally, the adventurer can function normally underwater, in space, within the cone of a volcano, etc. It fails quickly (1d4 rounds) in the presence of super-intense conditions such as actual lava or the massive radiation of a melting nuclear core, for example.<br><i>Environmental protection</i> reduces damage from like sources by 4 (6 with a raise). If protecting against intense heat, for example, it protects against a flamethrower or <i>bolt</i> with a fire Trapping.",
    pageNum: 161,
    powerModifiers: ["2"],
    id: "25",
    name: "Environmental Protection",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary:
      "See detail at great distance; halves Range penalties with a raise.",
    trappings: ["Invisibly marked targets", " guiding winds", " eagle eyes."],
    fullDescription:
      "<i>Farsight</i> allows the recipient to see in detail over great distances. They can read lips or read fine print up to a mile distant.<br>With a raise, they also halve Range penalties for Shooting, Athletics (throwing), or other abilities affected by Range.",
    pageNum: 161,
    powerModifiers: ["2"],
    id: "26",
    name: "Farsight",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Causes Fear check.",
    trappings: ["Gestures", " eldritch energy", " cold chills."],
    fullDescription:
      "<i>Fear</i> causes overwhelming dread and horror. The affected make a Fear roll. Extras who fail are Panicked and Wild Cards roll on the <strong>Fear Table</strong>. If the power is cast with a raise, the Fear roll is at -2 and Wild Cards add +2 to <strong>Fear Table</strong> results.",
    pageNum: 161,
    powerModifiers: ["13", "11"],
    id: "27",
    name: "Fear",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Target flies at Pace 12&quot;.",
    trappings: ["Gusty winds", " wings", " broomsticks."],
    fullDescription:
      "<i>Fly</i> allows a character to soar at Pace 12&quot;, or twice that with a raise (he may not Run).",
    pageNum: 162,
    powerModifiers: ["4"],
    id: "28",
    name: "Fly",
    relatedPowers: [],
  },
  {
    alternateName: "Shrink/Growth",
    rank: undefined,
    powerPoints: "Special",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Increases or decreases Size.",
    trappings: ["Gestures", " words of power", " potions."],
    fullDescription:
      "<i>Growth</i> increases the recipient's Size by 1 for every 2 Power Points spent. Each increase in Size grants the target a one-step increase to Strength and 1 point of Toughness (see page 178 for more on <strong><i>Size</i></strong>.) This does not increase Wounds regardless of change to Scale.<br><i>Shrink</i> reduces the Size of the subject one step for every 2 Power Points spent to a maximum of Size -2 (approximately the size of a cat). Each step reduced decreases Strength one die type (minimum of d4) and Toughness by 1 (minimum of 2).<br>For unwilling targets, the caster's arcane skill roll is opposed by Spirit.",
    pageNum: 162,
    powerModifiers: ["33"],
    id: "29",
    name: "Growth/Shrink",
    relatedPowers: [],
  },
  {
    alternateName: "Pummel",
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Targets in MBT or Cone are Distracted and may be hurled.",
    trappings: ["Whirlwind", " chaotic poltergeists", " repulsion field."],
    fullDescription:
      "<i>Havoc</i> creates chaos and mischief for all those within its area of effect, hurling debris and rivals in all directions.<br>With success, the caster places a Medium Blast Template anywhere within Range, or a Cone Template emanating from the caster (see <strong>Area Effect Attacks</strong>, page 97).<br>Anyone touched by the template is Distracted and must <i>then</i> make a Strength roll (at -2 if the caster got a raise). Those who fail are hurled 2d6&quot;directly away from the caster if using the Cone Template or directly away from the center if using a Blast Template (the caster chooses for those in the dead center).<br>Victims who strike a hard object (such as a wall) take 2d4 damage (nonlethal unless it's a spiked wall or other more dangerous hazard).<br><strong>Airborne Targets:</strong> Flying or airborne targets suffer an additional -2 to their Strength rolls as they have no ground to brace themselves on.",
    pageNum: 162,
    powerModifiers: ["58", "8"],
    id: "30",
    name: "Havoc",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Touch",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Restores Wounds less than an hour old.",
    trappings: [
      "Laying on hands",
      " touching the victim with a holy symbol",
      " prayer.",
    ],
    fullDescription:
      "<i>Healing</i> removes Wounds less than an hour old. A success removes one Wound, and a raise removes two. The power may be cast additional times to remove additional Wounds within that hour and as long as the healer has enough Power Points.<br>For Extras, the GM must first determine if the ally is still alive (see <strong>Aftermath</strong>, page 96). If so, a successful arcane skill roll returns the ally to action (Shaken if it matters.)",
    pageNum: 162,
    powerModifiers: ["41", "32", "23"],
    id: "31",
    name: "Healing",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Creates imaginary images.",
    trappings: [
      "Magical spells",
      " holograms",
      " &quot;ethereal materializes.&quot;",
    ],
    fullDescription:
      "One of the greatest powers is the ability to create something from nothing&#8212;even if it's not real!<br><i>Illusion</i> can be used to create a visual scene or replica of most anything the caster can imagine, but it is silent, intangible, and incapable of affecting the real world. For example, illusionary weapons pass through foes, one cannot sit in an illusionary chair, and an illusionary dog has no audible bark.<br>Those who contact an <i>illusion</i> or doubt it's real make a Smarts roll as a free action (at -2 if the power was activated with a raise). If successful, that individual is no longer subject to this casting.<br>The GM should make group rolls for Extras as they point out the <i>illusion's</i> inconsistencies to each other.<br>The volume of the <i>illusion</i> must fit within a sphere the size of a Medium Blast Template (4&quot; or eight yards in diameter).",
    pageNum: 163,
    powerModifiers: ["61", "55"],
    id: "32",
    name: "Illusion",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "5",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Target becomes incorporeal.",
    trappings: ["Ghost form", " body of shadow", " gaseous transformation."],
    fullDescription:
      "With a successful arcane skill roll, whoever receives this power becomes incorporeal. They are unable to affect the physical world, and it cannot affect them. They can travel through walls, and non-magical weapons pass straight through them. Any items carried at the time of casting are also incorporeal.<br>While incorporeal, the character may affect other incorporeal beings (including themselves), and they are still susceptible to supernatural attacks, including powers and enchanted items.<br>The being becomes corporeal when the power ends, but if within someone or something he's shunted to the nearest open space and Stunned.<br>If cast on an unwilling target, the victim resists with Spirit.",
    pageNum: 163,
    powerModifiers: [],
    id: "33",
    name: "Intangibility",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "5",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Target is invisible (-4/-6 to affect).",
    trappings: ["Powder", " potion", " iridescent lights."],
    fullDescription:
      "With a success, the character and his personal items are transparent except for a vague blur or outline. Any action taken against him that requires sight is made at -4, or -6 with a raise. The same penalty applies to Notice rolls to detect the unseen presence.",
    pageNum: 164,
    powerModifiers: ["5"],
    id: "34",
    name: "Invisibility",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 10,
    summary: "Creates illumination.",
    trappings: ["Illusionary torch", " sunlight."],
    fullDescription:
      "<i>Light</i> creates bright illumination in a Large Blast Template. With a raise, the light can be focused into a 5&quot; (10 yard) beam as well.<br>If <i>light</i> and <i>darkness</i> overlap, they create a patch of Dim light (-2).",
    pageNum: 164,
    powerModifiers: ["38"],
    id: "35",
    name: "Light",
    relatedPowers: ["14"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Decreases a skill or attribute.",
    trappings: ["Physical change", " glowing aura", " potions."],
    fullDescription:
      "This power allows a character to increase or decrease a target's Trait (attribute or skill).<br><i>Lowering</i> an enemy's Trait has a Duration of Instant and lowers the selected attribute or skill a die type with success, or two with a raise (to a minimum of d4). A victim automatically tries to shake off the effect with a Spirit roll as a free action at the end of his following turns. Success improves the effect one die type, and a raise removes the effect entirely.<br>Additional castings don't stack on a single Trait (take the highest), but may affect different Traits.",
    pageNum: 156,
    powerModifiers: ["59", "2"],
    id: "36",
    name: "Lower Trait",
    relatedPowers: ["8"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 30,
    summary: "Mental link within one mile (5 with raise).",
    trappings: ["Headpieces", " talismans of Tao or other gods", " crystals."],
    fullDescription:
      "<i>Mind link</i> creates a telepathic connection between two individuals (which does not necessarily have to include the caster). The link accommodates only willing subjects and communication&#8212;thoughts that aren't consciously transmitted aren't relayed.<br>Once activated, the Range between all linked minds is one mile, or five with a raise.<br>If any of the linked characters suffers a Wound, all others must make a Smarts roll or be Shaken (this cannot cause a Wound).<br>The speed of communication is that of normal speech, but with a raise members may communicate up to 30 seconds or so of speech on a single combat turn.",
    pageNum: 164,
    powerModifiers: ["2"],
    id: "37",
    name: "Mind Link",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Opposed roll vs Smarts to read mind.",
    trappings: ["Psionic invasion", " soulsight."],
    fullDescription:
      "<i>Mind reading</i> is an opposed roll versus the target's Smarts. Success allows the character to gain one truthful answer from the subject. The target is aware of the mental intrusion unless the mind reader gets a raise. The GM may apply modifiers based on the subject's mental Hindrances or current state of mind.",
    pageNum: 164,
    powerModifiers: [],
    id: "38",
    name: "Mind Reading",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Removes and alters memories.",
    trappings: [
      "A noxious drink",
      " parasites",
      " touching the target's temples.",
    ],
    fullDescription:
      "<i>Mind wipe</i> removes a target's memories, a terrible violation in most civilized societies. The power is opposed by a victim's Smarts and requires a full minute of mental struggle. The victim must be conscious during this time, so if not restrained he can simply move out of Range.<br>If successful, the victim forgets a single event (up to about 30 minutes of time). A raise removes a complex memory of several hours.<br>If the defender wins, the caster cannot affect him with mind wipe for 24 hours. (Others may reattempt the power, however.)<br>The memory remains missing but strong evidence that challenges its &quot;logic&quot; allows a Smarts roll at -2 to remember fragments determined by the GM.",
    pageNum: 165,
    powerModifiers: ["30", "29"],
    id: "39",
    name: "Mind Wipe",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Touch",
    rangeMultiplier: null,
    duration: "Special",
    durationMultiplier: null,
    summary:
      "Reveals last five years of an object's history (100 years with a raise).",
    trappings: ["Touching the object", " glowing hands"],
    fullDescription:
      "<i>Object reading</i> is the ability to see the past of an inanimate object, discovering who held it, where it's been, and what it might have been used for. The object has no sentience of its own&#8212;the caster simply sees and hears visions of the past that took place in its presence.<br>Success allows the character to see events that occurred within 10 yards up to about five years past. A raise increases this to 100 years and 20 yards. The caster can &quot;fast forward&quot; and &quot;rewind&quot; as desired, skimming about 10 years of history per minute of real time. When watching an actual event, it occurs in real time, just as if watching a digital video.",
    pageNum: 165,
    powerModifiers: ["16"],
    id: "40",
    name: "Object Reading",
    relatedPowers: [],
  },
  {
    alternateName: "Armor",
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Grants Armor +2/+4.",
    trappings: [
      "A mystical glow",
      " hardened skin",
      " ethereal armor",
      " a mass of nanites.",
    ],
    fullDescription:
      "<i>Protection</i> creates a field of energy or armor around a character, giving him 2 points of Armor, or +4 with a raise.<br>Whether the <i>protection</i> is visible or not depends on the Trapping&#8212;this is entirely up to the caster.<br><i>Protection</i> doesn't normally stack with other armor, but see the <strong>Toughness </strong>modifier.",
    pageNum: 165,
    powerModifiers: ["69", "40", "2"],
    id: "41",
    name: "Protection",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Opposed roll vs Spirit to control target.",
    trappings: [
      "Glowing eyes",
      " trance-like state",
      " a swinging pocket watch",
      " voodoo dolls.",
    ],
    fullDescription:
      "<i>Puppet</i> is an opposed roll of the character's arcane skill versus the target's Spirit. With success, the victim automatically obeys commands that don't directly harm himself or those he cares about.<br>With a raise, the target is completely controlled, but gets an automatic Spirit roll as a free action to avoid directly harming himself or those he cares about. If the <i>puppet's</i> resistance succeeds, he doesn't carry out that particular command but doesn't otherwise resist his master. With a raise, he breaks the controller's hold and the power ends.<br>Commands are general, such as &quot;attack that person&quot; or &quot;open that door.&quot; The controller doesn't get to dictate how many actions the victim uses in a turn, whether or not he uses his Sweep Edge, etc.",
    pageNum: 165,
    powerModifiers: ["4"],
    id: "42",
    name: "Puppet",
    relatedPowers: [],
  },
  {
    alternateName: "Succor",
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Removes Fatigue, Shaken; & Stun with raise.",
    trappings: ["Prayer", " tonics."],
    fullDescription:
      "<i>Relief</i> removes one Fatigue level, or two with a raise. It can also remove a character's Shaken status, and removes Stunned status with a raise.",
    pageNum: 166,
    powerModifiers: ["2"],
    id: "43",
    name: "Relief",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "30",
    range: "Touch",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Brings the dead back to life.",
    trappings: [
      "Elaborate ceremonies",
      " rare plants",
      " magical amulets",
      " divine intervention",
    ],
    fullDescription:
      "Perhaps the greatest power of all is the ability to bring someone back from the dead. It can restore lost loves, bring solace to the grieving, and topple kingdoms.<br>Returning the dead to life requires a reasonably complete corpse no more than a year old. The caster then prays, meditates, chants, or otherwise concentrates on mending the body and pulling the spirit back to it for four hours.<br>Once done, the healer makes a casting roll at -8. If successful, the victim returns to life with three Wounds and is Exhausted. With a raise, they return merely Exhausted.",
    pageNum: 166,
    powerModifiers: ["45"],
    id: "44",
    name: "Resurrection",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "Special",
    range: "Self",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Caster takes on the form of various beings.",
    trappings: ["&quot;Morphing", "&quot; talismans", " tattoos."],
    fullDescription:
      "Many cultures have legends of shamans or wizards who take on the shape of animals. This power does just that, allowing the caster to take the form of any animal (including fantastic creatures such as dragons and hippogriffs if they exist in that setting, but not humanoids, undead, etc).<br>What a character can change into depends on his Rank:<br><table><tr><th colspan=3>SHAPE CHANGE</th></tr>  <tr><th>COST</th><th>RANK</th><th>SIZE<th></tr>  <tr><th>3</th><th>Novice Size</th><th>-4 to Size -1<th></tr>  <tr><th>5</th><th>Seasoned</th><th>Size 0<th></tr>  <tr><th>8</th><th>Veteran</th><th>Size +1 to +2<th></tr>  <tr><th>11</th><th>Heroic</th><th>Size +3 to +4<th></tr>  <tr><th>15</th><th>Legendary</th><th>Size +5 to +10<th></tr></table><br>With a raise on the roll, the character transforms into a particularly large version of its type&#8212;increase its Strength and Vigor by one die type each.<br>Weapons and other personal effects are assumed into the animal's form and reappear when the power ends, but other objects are dropped.<br>While transformed, the character retains his own Smarts, Spirit, Hindrances, Edges, and linked skills (though he may not be able to use some or all of them depending on the form&#8212; GM's call). They gain the animal's Agility, Strength, Vigor, and linked skills and cannot use devices that require humanoid form. They have no capacity for speech and cannot activate powers, though they may continue to maintain powers previously activated.<br>A creature's natural abilities inherent to its form are conferred, but magical ones aren't. A dragon can fly and breathe fire in a traditional fantasy setting, for example, a character who shape changes into one may do so as well. If dragons also cast spells in that world, however, shape change would not grant that ability because it's not inherent to the physical form.<br><strong>Size:</strong> The caster does not inherit extra Wounds when transforming into creatures of Large or Huge <strong>Scale</strong> (page 179).",
    pageNum: 166,
    powerModifiers: ["56", "51", "50", "49", "48", "47"],
    id: "45",
    name: "Shape Change",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Mute sound.",
    trappings: [
      "Magical effects",
      " a brief ripple in the air",
      " a bell or chime that stops ringing.",
    ],
    fullDescription:
      "<i>Silence</i> mutes all sound up to a loud shout within a Large Blast Template. This subtracts 4 from Notice rolls made by those inside the area of effect, as well as anyone trying to hear sounds made from within. A raise completely mutes all sound inside the template&#8212;such Notice rolls automatically fail.",
    pageNum: 168,
    powerModifiers: ["67", "39"],
    id: "46",
    name: "Silence",
    relatedPowers: ["50"],
  },
  {
    alternateName: "Slow",
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Decreases movement.",
    trappings: ["Slowing time", " blurred motion."],
    fullDescription:
      "<i>Sloth</i> lessens celerity and coordination. It halves the target's total movement each round (round up). With a raise, movement is also an action. The target automatically attempts to shake off the effects of sloth at the end of each of his next turns by making a Spirit roll.",
    pageNum: 167,
    powerModifiers: ["59", "13", "11"],
    id: "47",
    name: "Sloth",
    relatedPowers: ["52"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Hour",
    durationMultiplier: 1,
    summary: "Puts victims to sleep.",
    trappings: ["A lullaby", " blowing powder or sand at targets."],
    fullDescription:
      "Those who favor stealth or want to avoid harming their foes are drawn to this spell, which puts its victims into a deep and restful sleep.<br>Anyone affected by slumber must make a Spirit roll (at -2 if the caster got a raise on their arcane skill roll). Those who fail fall asleep for the Duration of the spell. Very loud noises or attempts to physically wake a sleeper (by shaking them, for example), grant another Spirit roll.",
    pageNum: 167,
    powerModifiers: ["13", "11"],
    id: "48",
    name: "Slumber",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Increase a weapon's damage by +2/+4.",
    trappings: [
      "A colored glow",
      " runes",
      " sigils",
      " crackling energy",
      " barbs grow from the blade.",
    ],
    fullDescription:
      "This power is cast on a weapon of some sort. If it's a ranged weapon, it affects one entire magazine, 20 bolts, shells, or arrows, or one full &quot;load&quot; of ammunition (the GM determines the exact quantity for unusual weapons). While the power is in effect, the weapon's damage is increased by +2, or +4 with a raise.",
    pageNum: 168,
    powerModifiers: ["2"],
    id: "49",
    name: "Smite",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: 5,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Create sound.",
    trappings: [
      "Magical effects",
      " a brief ripple in the air",
      " a bell or chime that starts ringing.",
    ],
    fullDescription:
      "<i>Sound</i> mimics any known sound or voice, emanating from a point of origin within Range at a volume up to the sound of a loud shout. If used as a Test, the defender opposes the casting roll with Smarts.",
    pageNum: 168,
    powerModifiers: ["39"],
    id: "50",
    name: "Sound",
    relatedPowers: ["46"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "1",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Minutes",
    durationMultiplier: 10,
    summary: "Caster can speak and understand languages.",
    trappings: ["Words", " pictures", " hand motions."],
    fullDescription:
      "<i>Speak language</i> allows a character to speak, read, and write a sapient language other than his own. A raise on the arcane skill roll allows the user to appropriately use and understand slang and dialect as well.",
    pageNum: 168,
    powerModifiers: ["2"],
    id: "51",
    name: "Speak Language",
    relatedPowers: [],
  },
  {
    alternateName: "Quickness",
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Increases movement.",
    trappings: ["A slippery patch of oil or ice."],
    fullDescription:
      "<i>Speed</i> increases celerity and coordination. It doubles the target's movement (basic Pace and running). With a raise the character also ignores the -2 running penalty.",
    pageNum: 167,
    powerModifiers: ["46", "2"],
    id: "52",
    name: "Speed",
    relatedPowers: ["47"],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Target is Stunned.",
    trappings: [
      "Bolts of energy",
      " stun bombs",
      " sonic booms",
      " burst of blinding light.",
    ],
    fullDescription:
      "<i>Stun</i> shocks a target with concussive force, sound, light, magical energy, or the like.<br>A successful casting means the victim must make a Vigor roll (at -2 with a raise on the arcane skill roll) or be <strong>Stunned</strong> (see 106).",
    pageNum: 168,
    powerModifiers: ["13", "11"],
    id: "53",
    name: "Stun",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "Special",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Conjures an ally of various sorts.",
    trappings: [
      "Clay figure that grows into a servant",
      " a tattoo that comes to life.",
    ],
    fullDescription:
      "This power allows the character to summon a magical servant from nothing. The ally typically takes the form of a basic humanoid of the appropriate Size but can appear differently based on the caster's trappings. It materializes anywhere in Range, and with a raise on the arcane skill roll, it's Resilient as well.<br>The ally acts on its creator's Action Card and follows her commands to the best of its ability. It has no personality, creativity, or emotions. When the power ends or the ally is Incapacitated, it fades into nothingness, leaving no trace behind.<br>The type of servant that can be summoned depends on the caster's Rank. With the GM's approval, the player may swap abilities. If a hero wants an attendant in the form of a wolf, for example, the caster might exchange the Shooting skill for Survival so that the &quot;animal&quot; can track its foes.<br><table><tr><th colspan=3>SUMMON ALLY</th></tr><tr><th>RANK</th><th>COST</th><th>SERVANT</th></tr><tr><td>Novice</td><td>2</td><td>Attendant</td></tr><tr><td>Seasoned</td><td>4</td><td>Bodyguard</td></tr><tr><td>Veteran</td><td>6</td><td>Mirror Self*</td></tr><tr><td>Heroic</td><td>8</td><td>Sentinel</td></tr><tr><td colspan=3><i>* Mirror Self costs +2 power points per Rank above Veteran to a maximum of 10 PPs at Legendary.</i></td></tr></table>",
    pageNum: 169,
    powerModifiers: ["66", "65", "64", "63", "37", "31", "22"],
    id: "54",
    name: "Summon Ally",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "5",
    range: "Smarts",
    rangeMultiplier: 2,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Moves items with Strength of d10 (d12 with a raise).",
    trappings: ["A wave of the hand", " magic wand", " steely gaze."],
    fullDescription:
      "<i>Telekinesis</i> is the ability to move objects or creatures (including oneself) with arcane will. It has a Strength of d10, or d12 with a raise.<br>Unwilling opponents resist the caster's arcane skill with an opposed Spirit roll when targeted and at the start of each of their turns afterward until they're released. They can be moved up to the caster's Smarts per turn in any direction, and can be bashed into walls, ceilings, or other obstacles for Str+d6 damage.<br>Dropped creatures suffer falling damage as usual.<br><strong>Telekinetic Tools: </strong>A caster can wield tools (including weapons) with telekinesis as an action. Use the caster's relevant skill when attacking in this way (not his arcane skill).",
    pageNum: 170,
    powerModifiers: [],
    id: "55",
    name: "Telekinesis",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Instant",
    durationMultiplier: null,
    summary: "Character teleports up to 12&quot; distant.",
    trappings: [
      "A cloud of smoke",
      " &quot;phasing&quot; out",
      " change into a bolt of lightning.",
    ],
    fullDescription:
      "<i>Teleport</i> allows a character to disappear and instantly reappear up to 12&quot; (24 yards) distant, or double that with a raise. Teleporting to an unseen location incurs a -2 penalty on the arcane skill roll.<br>Opponents adjacent to a character who teleports away don't get a free attack (see <strong>Withdrawing from Melee</strong>, page 109).<br>If casting teleport on a willing subject, the caster decides where they move to, not the target.",
    pageNum: 170,
    powerModifiers: ["68", "2"],
    id: "56",
    name: "Teleport",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "2",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Character can walk on walls at half Pace (full Pace with raise).",
    trappings: ["Spider-like visage", " prickly hairs on hands and feet."],
    fullDescription:
      "<i>Wall walker</i> allows the recipient to walk on vertical or horizontal surfaces. With success, they move at half their normal Pace. With a raise, they may move at full Pace and even run.<br>If forced to make an Athletics roll to climb or hang on to a surface, they adds +4 to the total.",
    pageNum: 170,
    powerModifiers: ["2"],
    id: "57",
    name: "Wall Walker",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "4",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Rounds",
    durationMultiplier: 5,
    summary: "Grant target a Combat Edge.",
    trappings: ["Gestures", " prayer", " whispered words", " concentration."],
    fullDescription:
      "With a successful arcane skill roll, the recipient gains the benefits of a single Combat Edge chosen by the caster. The caster (not the recipient) must have the same Rank or higher as the Edge's Requirements. With a raise, the recipient gains the Improved version of the Edge (if there is one, and even if he doesn't meet the Rank Requirement).",
    pageNum: 170,
    powerModifiers: ["2"],
    id: "58",
    name: "Warrior's Gift",
    relatedPowers: [],
  },
  {
    alternateName: null,
    rank: undefined,
    powerPoints: "3",
    range: "Smarts",
    rangeMultiplier: null,
    duration: "Hour",
    durationMultiplier: 1,
    summary: "Raises and controls the undead.",
    trappings: [
      "Carving symbols on corpses",
      " throwing bones",
      " graveyards",
      " &quot;leather&quot; books.",
    ],
    fullDescription:
      "<i>Zombie</i> grants animation and basic intelligence to the remains of a once-living being. The summoned horror is obedient but literal-minded in its duties. It isn't telepathic, and must be controlled by voice.<br>The being has the physical skills it had in life, but its Smarts, Spirit, and related skills are reset to d4. A raise on the casting roll increases any one of their Traits by one die type (caster's choice).<br>See page 191 for the standard profile of a human zombie. Corpses aren't summoned by this ability, so there must actually be a supply of bodies in Range (GM's call).<br>An undead Incapacitated by damage can't be raised with this power again.",
    pageNum: 170,
    powerModifiers: ["42", "36", "15", "14", "6"],
    id: "59",
    name: "Zombie",
    relatedPowers: [],
  },
];
